### ISSUE TITLE
beta-group-significance: automatically filter metadata to match feature table samples

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-diversity#107]
It would be great to have sample metadata automatically filter to match the samples in a feature table when running beta-group-significance (or similar methods, for that matter, that might cause the same error). This is a frequent issue, e.g., when subsetting a large feature table, or if samples are filtered out due to low coverage.

I recognize there are probably good reasons to produce this error instead of automatically filtering. Alternatively, there should at least be either 1) a parameter to toggle auto-filtering on/off, or 2) a method to filter a metadata file, to produce a new metadata file containing just those samples, and an option to automatically run such a method whenever a feature table or distance matrix is filtered (there could be good reasons to have a method do this, not just manually, e.g., if some samples were filtered due to low coverage in a large sample set).

The specific error I'm getting associated with this issue is this:

```
Plugin error from diversity:

  All samples in distance matrix must be present and contain data in the
  sample metadata. The following samples were present in the distance
  matrix, but were missing from the sample metadata or had no data: sample1...
```

**Comment by ebolyen** [comment]
I ran across subsetting behavior on the forum w.r.t. beta-group-significance, and it does basically what you are suggesting (leading me to this issue). @nbokulich can this issue be closed or is it talking about a different action?

**Comment by nbokulich** [comment]
Yes, it looks like this can be closed (this issue is old — and appears to be addressed on [this
 line](https://github.com/qiime2/q2-diversity/blob/master/q2_diversity/_beta/_visualizer.py#L138))
 — thanks @ebolyen !
