### ISSUE TITLE
Expose, or support, sklearn.metrics.pairwise_distances in beta/alpha diversity methods

### ISSUE THREAD

**Issue by jakereps** [qiime2/q2-diversity#108]
Currently the `beta` and `alpha` diversity methods use [`scipy.spatial.distance.pdist`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.pdist.html) (through the default method for `skbio`). `sklearn` offers a pairwise distance function ([`sklearn.metrics.pairwise_distances`](http://scikit-learn.org/stable/modules/generated/sklearn.metrics.pairwise_distances.html#sklearn.metrics.pairwise_distances)) that utilizes the same scipy method internally, but also allows parallelization (and adds a few other metrics of their own). 

Here's a small example benchmark:
![image](https://user-images.githubusercontent.com/2638727/27044397-5370f674-4f52-11e7-843b-4e3fbb8ddf9b.png)

Could this alternative function be either swapped as the default function used, or made available as an option of some sort, where the existing behavior could even remain the same just a `n_jobs` parameter added that defaults to 1? 

It could possibly be made as an optional parameter where the description disclaims that it 'requires sklearn' or something in the parameter description, without requiring `sklearn` to be added as another dependency, and the import can be wrapped in a try/except ImportError block.

**Comment by jairideout** [comment]
:+1: I'm in favor of making `sklearn` the backend and exposing an `n_jobs` parameter. It shouldn't be a problem making `sklearn` a dependency since it's already a dependency of `q2-feature-classifier` (so most QIIME 2 users are already required to have it installed).

@ebolyen @gregcaporaso thoughts? Could be nice incremental improvement while we're waiting on pipeline support.

**Comment by ebolyen** [comment]
I don't think there's any reason not to. Someday we'll be able to get a joblib backend directly from the execution context, but until then, using single-node parallelism sounds nice.
