### ISSUE TITLE
make `phylogeny` optional in core-metrics

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-diversity#112]
Ported from @antgonza's [comment](https://github.com/qiime2/qiime2/issues/235#issuecomment-298924297). Also came up on the forum in [this topic](https://forum.qiime2.org/t/core-metrics-without-phylogeny/767/3) and [this topic](https://forum.qiime2.org/t/how-to-connect-to-a-supercomputer-server/1061/7).

It would be really handy to make the `phylogeny` parameter optional, once optional artifacts are supported in QIIME 2 (open PR: https://github.com/qiime2/qiime2/pull/289). This would allow users to run non-phylogenetic analyses, which is important e.g. with ITS data. QIIME 1's core_diversity_analyses.py has similar support (`--nonphylogenetic_diversity` flag).

**Comment by ebolyen** [comment]
How would we handle the return? It seems like we would need variadic outputs.

**Comment by jakereps** [comment]
`q2-deblur` handles it by just dumping out an empty file (or `Result` through the API) for the optional stats file. Not sure how "elegant" that is, but it seems to work for that plugin as a stop-gap for this.

**Comment by jairideout** [comment]
@ebolyen, that's a good point about the outputs becoming variadic (or dynamic based on supplied inputs). @jakereps, I'm not sure that q2-deblur's workaround will help us here because there isn't an appropriate "empty" output that can be created for the phylogenetic metrics -- for example, it's not possible to create an empty distance matrix for weighted/unweighted UniFrac.

Perhaps we could have a non-phylogenetic `core-metrics` method instead, similar to `beta`/`beta-phylogenetic`?

**Comment by jakereps** [comment]
Separate methods definitely make more sense. I should clarify `q2-deblur` wasn't "empty", but had fake data. So something like this even passes `skbio`'s LSMat sniffer:

![image](https://user-images.githubusercontent.com/2638727/27664281-8e1df86e-5c1b-11e7-9a48-1de1f3ac2313.png)

Either way it's confusing to get it back when it's "optional," and would be even more confusing in the case of the ~10 output `core-metrics` method.

**Comment by jairideout** [comment]
Thanks for the details @jakereps and for clarifying what q2-deblur is doing. Sounds like there's consensus on adding a new method so let's go with that design.

I'd like to try to get this feature in for 2017.7 since it's been requested a few times now and the current workaround is pretty inconvenient. QIIME 2 has been adding more support for ITS data so this new method would fit perfectly into that track. If anyone is available to work on this please let me know!

**Comment by thermokarst** [comment]
> Perhaps we could have a non-phylogenetic core-metrics method instead, similar to beta/beta-phylogenetic?

Would this looks like `core-metrics` and `core-metrics-phylogenetic`? This option would mirror the `beta` example nicely, but would completely change the meaning of `core-metrics`.

Or, is something like `core-metrics` and `core-metrics-non-phylogenetic` better (I don't think so)? 🍶

**Comment by thermokarst** [comment]
After discussing with @jairideout offline, we are going to go with `core-metrics` and `core-metrics-phylogenetic`. This will change the meaning of `core-metrics`, but this should be a straightforward change to users, and the safety net is pretty sturdy for anyone who might try and feed a phylogeny into the new `core-metrics`: they will be gently guided in the right direction (what will QIIME 2 do to you?).
