### ISSUE TITLE
add procrustes method

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-diversity#120]
I *think* this should take two PCoA matrices (say `pcoa-a` and `pcoa-b`) as input, and output one PCoA matrix, where the output matrix is the `pcoa-b` transformed to minimize differences against `pcoa-a`.

**Comment by ElDeveloper** [comment]
Is there a timeline for this, I would like to make sure that this feature exists in Emperor before this is planned to exist.

**Comment by jairideout** [comment]
We're planning to add it in the 2017.9 release. Does that timeline work for you?

**Comment by ElDeveloper** [comment]
Yes, I think this should work!!

**Comment by jairideout** [comment]
Cool! Get in touch with us on Slack if you want to coordinate anything for the next release cycle.

**Comment by ElDeveloper** [comment]
I have opened [this PR](https://github.com/biocore/emperor/pull/647) in emperor that adds the ability to plot procrustes plots. One key difference from the plots in QIIME 1 is that it allows you to add a description for each matrix you want to compare. This is useful for example when you compare three rarefaction levels and you want to see which matrix represents which rarefaction.
