### ISSUE TITLE
multi-way PERMANOVA

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-diversity#123]
PERMANOVA and Adonis currently only support one-way group comparisons in `q2-diversity`.

However, the [vegan-R versions](http://cc.oulu.fi/~jarioksa/softhelp/vegan/html/adonis.html) accept functions as input to support multi-way comparisons (e.g., beta diversity differences as a function of an individual's age, BMI, zodiac sign). 

That would be **awesome** to support in `q2-diversity`.

@mortonjt 's comments in [this q2-sample-classifer` issue](https://github.com/nbokulich/q2-sample-classifier/issues/30) may prove useful here, re: how to input a formula to test interactions between variables.

**Comment by jairideout** [comment]
:+1:, this question came up a couple of times at the STAMPS workshop and should be high priority. Without support for covariates, users are often not running the correct tests for their data/study design (i.e. they're not testing what they think they're testing for).

**Comment by cuttlefishh** [comment]
It would be great to see multi-way PERMANOVA as well as other methods from vegan. I had discussions with vegan creator Jari Oksanen about adapting vegan functions for Python last week in Oulu. Presumably this would be part of q2-diversity rather than a future q2-vegan plugin. Also see issue #186.

**Comment by nbokulich** [comment]
[forum xref](https://forum.qiime2.org/t/adding-more-functions-to-permanova/4729)

**Comment by nbokulich** [comment]
[forum xref](https://forum.qiime2.org/t/adjusted-permanova/5009)
