### ISSUE TITLE
Export data from alpha_group_significance

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-diversity#133]
This came up on [the forum](https://forum.qiime2.org/t/link-to-raw-data-behind-figures/650/4?u=thermokarst).

**Comment by thermokarst** [comment]
This came up again on[ the forum](https://forum.qiime2.org/t/alpha-diversity-box-plots/1241/1).

**Comment by nbokulich** [comment]
and again [on forum](https://forum.qiime2.org/t/raw-data-for-alpha-diversity-boxplots/4331)
