### ISSUE TITLE
`alpha` help docs should provide url reference for skbio alpha diversity metrics

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-diversity#167]
**Comments**
Maybe the relevant docs tutorial(s) should also provide this url.

**References**
1. Came up in [this forum post](https://forum.qiime2.org/t/alpha-diversity-metrics/1879)
2. I believe [this is the appropriate url](http://scikit-bio.org/docs/0.2.0/generated/skbio.diversity.alpha.html), but maybe there is a better one.

**Comment by jairideout** [comment]
That URL is *really* old (skbio 0.2.0), recommend using the "latest" URL: http://scikit-bio.org/docs/latest/generated/skbio.diversity.alpha.html

**Comment by ChrisKeefe** [comment]
If this is something we still want to add, it should be trivial to do so. 

Sample language here:
![image](https://user-images.githubusercontent.com/39198770/90581764-dee78600-e180-11ea-879f-ebef8028e10e.png)


How do we feel about using a link shortener to clean this URL up? If that's a good idea, do we have a preferred shortener for this project, or should I just choose one?

**Comment by thermokarst** [comment]
> do we have a preferred shortener

https://github.com/qiime2/data302
