### ISSUE TITLE
distance group comparisons

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-diversity#17]
**Improvement Description**
- [x] first priority are ~~PERMANOVA~~ (it's done!) and PERMDISP, based on [this paper](http://onlinelibrary.wiley.com/doi/10.1890/12-2010.1/abstract), and default should compute both (this is related to biocore/scikit-bio#1228)
- [x] third priority is ANOSIM

**Comments**
1. All of these (and others that should be added) with the exception of PERMDISP are currently in scikit-bio ([docs here](http://scikit-bio.org/docs/0.5.0/generated/skbio.stats.distance.html#distance-based-statistics)). 
2. **UPDATE (8 Mar 2018)**: A forum user/workshop attendee [brought up an interesting point](https://forum.qiime2.org/t/beta-group-significance-plots-not-representative-of-permanova-test/3320) about the plots presented in this visualization. I think ultimately we should update to new plots (possibly via Emperor?) that would illustrate the location of group centroids and the dispersion of samples from group centroids. 

**References**
1. [this paper](http://onlinelibrary.wiley.com/doi/10.1890/12-2010.1/abstract), and default should compute both (this is related to biocore/scikit-bio#1228)
2. [docs here](http://scikit-bio.org/docs/0.5.0/generated/skbio.stats.distance.html#distance-based-statistics)
3. [brought up an interesting point](https://forum.qiime2.org/t/beta-group-significance-plots-not-representative-of-permanova-test/3320)

**Comment by ElDeveloper** [comment]
@nreeve17 and I are working on adding permdisp to scikit-bio. We'll post about progress there:
https://github.com/biocore/scikit-bio/issues/1228

**Comment by gregcaporaso** [comment]
Thanks @ElDeveloper and @nreeve17 - this will be really useful! permdisp is an obvious missing piece in QIIME 2 at the moment.

**Comment by gregcaporaso** [comment]
@ElDeveloper, do you know the current status of this? It came up again on the forum this week ([x-ref](https://forum.qiime2.org/t/beta-group-significance-plots-not-representative-of-permanova-test/3320)).

**Comment by ElDeveloper** [comment]
@gregcaporaso We have not found someone who could commit to [reviewing the PR on scikit-bio](https://github.com/biocore/scikit-bio/pull/1532/). If you can have a look that would be wonderful.

**Comment by gregcaporaso** [comment]
I can do that, thanks for the reminder about the status!

**Comment by ElDeveloper** [comment]
Thanks, I appreciate it!

**Comment by gregcaporaso** [comment]
This has been done for a while.
