### ISSUE TITLE
Beta diversity metric `wminkowski` not enough args

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-diversity#170]
**Screenshots**
`weighted minkowski requires a weight vector w to be given`

---

**Comments**
This warrants looking at all of the alpha and beta diversity methods. Options for fixing include somehow providing the weight vector, or, removing that metric from the list of available metrics.

**References**
This recently [came up on the forum](https://forum.qiime2.org/t/beta-diversity-fails-when-metric-wminkowski/2240?u=thermokarst).

**Comment by ChrisKeefe** [comment]
Closing. Supplanted by #288.

**Comment by thermokarst** [comment]
Hey bud, I was here first!!

**Comment by thermokarst** [comment]
On a more serious note, I knew something sounded familiar when you brought this up recently, go figure we had an ancient issue laying around.
