### ISSUE TITLE
beta_phylogentic error rewriting not working as expected

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-diversity#176]
**Description**
The error rewriting related to Index matching in `beta_phylogenetic` did not work for a user on the forum.

**Steps to reproduce the behavior**
Provide a table that has features not found in the tree. Using tutorial data, you could use the table from the feature table from the FMT Tutorial and the tree from the Moving Pictures Tutorial.

```bash
wget -O fmt-table.qza https://docs.qiime2.org/2018.6/data/tutorials/fmt/table.qza
wget -O mp-tree.qza https://docs.qiime2.org/2018.6/data/tutorials/moving-pictures/rooted-tree.qza

qiime diversity beta-phylogenetic \
  --i-table fmt-table.qza \
  --i-phylogeny mp-tree.qza \
  --p-metric unweighted_unifrac \
  --o-distance-matrix NOPE-NOT-EVEN-CLOSE.qza \
  --verbose
```

**Expected behavior**
```bash
All ``feature_ids`` must be present as tip names in ``phylogeny``. ``feature_ids`` not corresponding to tip names (n=336): 28e2e6d2b41b825c4ae2ab437316304b b7794e3380251f49e4b6e7eca8b4d935 ...
...
```

What the user on the forum saw:

```bash
MissingNodeError: All ``otu_ids`` must be present as tip names in ``tree``. ``otu_ids`` not corresponding to tip names (n=15002): e2cc357ffe57e5d5d20d4cc929a9803e 40570145f37809857b3fd113bedfe52a ...
...
```

**Computation Environment**
- OS: Unknown
- QIIME 2 Release 2017.12

**Questions**
1. I am not able to recreate the error message as reported by the forum user using QIIME 2 2018.8.dev0. Can anyone recreate this?

**References**
1. [Original forum ref](https://forum.qiime2.org/t/error-in-diversity-beta-phylogenetic/2568?u=thermokarst)
2. [Code in question](https://github.com/qiime2/q2-diversity/blob/master/q2_diversity/_beta/_method.py#L73-L75)

**Comment by turanoo** [comment]
@thermokarst, I think this is a good issue for me to work on. Can you assign it to me?

**Comment by Oddant1** [comment]
The error we get now looks like this 

![image](https://user-images.githubusercontent.com/10642616/62397963-2d04f980-b52c-11e9-8920-7aece6f4685d.png)

It doesn't seem like this issue is a thing anymore

**Comment by thermokarst** [comment]
Yep, will close now.
