### ISSUE TITLE
add error bars to alpha rarefaction plots

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-diversity#179]
@jairideout brought this up in #130 - it was planned for the initial release, but didn't make it in. Separating this into it's own issue so it's easier to track on the project board.

**Comment by thermokarst** [comment]
@gregcaporaso, do you prefer error bars with horizontal lines:

<img width="1094" alt="screen shot 2018-02-01 at 7 52 30 am" src="https://user-images.githubusercontent.com/274668/35684688-ebc430a0-0724-11e8-8fe5-b72f01ed7546.png">

without:

<img width="1076" alt="screen shot 2018-02-01 at 7 53 52 am" src="https://user-images.githubusercontent.com/274668/35684749-18109536-0725-11e8-8f77-7b72ca66b36e.png">

or, some other third option, not listed here.

It is worth noting, error bar visibility is toggleable via the legend, same as the plot lines or plot symbols.

**Comment by gregcaporaso** [comment]
> do you prefer error bars with horizontal lines

I prefer with the horizontal lines, but I'm open to other opinions. I think it's more clear that they are error bars in that example.
