### ISSUE TITLE
alpha-group-significance viz not viewable at view.qiime2.org

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-diversity#187]
Related to #185 

[Sample viz](https://forum-qiime2-org.s3-us-west-2.amazonaws.com/original/2X/8/84ac8b522532667fa416309a058bfce985ab43b7.qzv). [q2view link](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fforum-qiime2-org.s3-us-west-2.amazonaws.com%2Foriginal%2F2X%2F8%2F84ac8b522532667fa416309a058bfce985ab43b7.qzv)

This recently [came up on the forum](https://forum.qiime2.org/t/error-plugin-error-from-diversity/3191/5?u=thermokarst).

**Comment by ebolyen** [comment]
Looking at the network requests, it looks like the spaces are getting [double-encoded somehow](https://stackoverflow.com/a/16085190). What's strange is the double encoding works for the `file://` protocol, but never succeeds on the client-end of the service-worker.

**Comment by thermokarst** [comment]
I think we are double-encoding the filenames, but I would need to check to be sure. This is ringing a bell.

**Comment by ebolyen** [comment]
Yeah it looks like the files in the zip are `%20` for spaces, but then that gets escaped in the browser as `%2520`, which is then converted back to `%20` for the `file://` protocol, but isn't converted in q2view. I don't think this is actually q2-diversity's fault.

**Comment by thermokarst** [comment]
This recently [came up on the forum](https://forum.qiime2.org/t/cant-see-faith-pd-group-qzv-plot-in-qiime2-view/3377).

**Comment by thermokarst** [comment]
Fixed in https://github.com/qiime2/q2view/pull/90
