### ISSUE TITLE
beta-rarefaction / jackknifed hierarchical clustering

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-diversity#19]

**Comment by ebolyen** [comment]
Jackknifing/bootstrapping is really easy to do with the new `TabularMSA` object, just generate a random index with [np.random.choice](http://docs.scipy.org/doc/numpy/reference/generated/numpy.random.choice.html)!

**Comment by gregcaporaso** [comment]
This would be jackknifing based on counts in a feature table (for clustering samples), not columns in a TablularMSA. Good to know for the future though.
