### ISSUE TITLE
"No such file" when viewing beta-group-significance visualization

### ISSUE THREAD

**Issue by antgonza** [qiime2/q2-diversity#197]
A visualization created with "qiime diversity beta-group-significance" and ~opened via q2view~ viewed using any available method will not load the images created. From @thermokarst, looks like a bug related to something in the metadata column names not being escaped correctly --- if you export the viz all the graphs are there, they just arent loading as expected in q2view

**Comment by ebolyen** [comment]
What are the column names?

**Comment by antgonza** [comment]
The column name is timepoint, my guess is that the problem are the values in the column, for example: "Post Stress (E2)"

**Comment by thermokarst** [comment]
@antgonza, I updated the title and the issue text to clarify - this issue has nothing to do with q2view, but rather with the `beta-group-significance` visualization not properly escaping some of the wrapped asset names.

@ebolyen, I believe there were `(` `)` characters in the MD labels.

**Comment by thermokarst** [comment]
Fixed in #264
