### ISSUE TITLE
Procrustes analysis should return an M2 statistic

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-diversity#210]
**Bug Description**
When performing the procrustes fitting an m^2 value is generated, however it is currently being ignored. What would be the best way to output this value?

**Comment by thermokarst** [comment]
Yikes - this is a bit of a hole in the framework right now. Your options include:

- Log to stdout. Users will only see this info if their interface supports seeing stdout logs (e.g. `--verbose` in q2cli)
- Create YAMF (yet another metadata-transformerable format). Examples of this include q2-dada2 & q2-deblur logging output artifacts.
- Update the visualization's HTML template to drop that info in somewhere.

I imagine there are more options, but those are the first to come to mind. Sorry I don't have better news for you, @ElDeveloper  💀 👎 😦 🚽

**Comment by ElDeveloper** [comment]
> Log to stdout. Users will only see this info if their interface supports seeing stdout logs (e.g. --verbose in q2cli)

Could work though it is very non-standard, and is likely to upset users.

> Create YAMF (yet another metadata-transformerable format). Examples of this include q2-dada2 & q2-deblur logging output artifacts.

Seems like an OK idea, though it would be a file that saves only a number.

> Update the visualization's HTML template to drop that info in somewhere.

Currently the visualization is only shown via Emperor, so we would still need an intermediary artifact to contain the M2.

Thanks for the info @thermokarst. Maybe the solution is to integrate the procrustes transformation with the plotting and the result would be to make a method that's called procrustes-analysis and that can save the M2 in the Emperor plot, say somewhere in the title of the plot.

**Comment by thermokarst** [comment]
> Currently the visualization is only shown via Emperor, so we would still need an intermediary artifact to contain the M2.

There is actually a wrapper template in q2-emperor: https://github.com/qiime2/q2-emperor/blob/master/q2_emperor/assets/index.html

Wouldn't this work?

**Comment by ElDeveloper** [comment]
It would still require an intermediary artifact, since the computation 
is done in q2-diversity and the plot is done in q2-emperor. It is true 
that the m2 value could be displayed in q2-emperor though.

**Comment by thermokarst** [comment]
lol, I am not a smart man. Sorry, wasn't paying attention to which repo this issue was in.

**Comment by ElDeveloper** [comment]
🙃 no worries. Is this a bigger issue that we should discuss somewhere 
else? Alternatively I could just try to implement any of options above.

**Comment by thermokarst** [comment]
Hmm, good question @ElDeveloper! For now, this seems appropriate, since this is a pretty concrete use-case. I will drop [this framework issue](https://github.com/qiime2/qiime2/issues/197) in here, too, for the sake of cross-referencing it (but I don't think it is necessarily where the discussion should live). I expect @ebolyen will chime in on this topic when he is back in the office next week.

**Comment by ElDeveloper** [comment]
OK, I'll wait until @ebolyen ~~qi~~chimes in and hopefully push something that will be available for the  2018.8 release.

**Comment by ElDeveloper** [comment]
Just to make sure I follow: For the time being I should create a new artifact for the M2 statistic? And add the ability for emperor to consume that artifact and display it with the plot's name?

**Comment by wasade** [comment]
Just a polite bump on this. It would be pleasant to obtain the M^2 and p-value from procrustes somehow as these are critical for interpretation

**Comment by gregcaporaso** [comment]
This was closed in #305.
