### ISSUE TITLE
ENH: alpha_correlation should have intersect_ids parameter

### ISSUE THREAD

**Issue by tkosciol** [qiime2/q2-diversity#259]
**Improvement Description**
similarly to `qiime2.plugins.diversity.pipelines.beta_correlation`, `qiime2.plugins.diversity.visualizers.alpha_correlation` should have the `intersect_ids` parameter

**Current Behavior**
Currently, for mismatches between alpha vector and metadata the visualizer produces an error

**Proposed Behavior**
intersect_ids and run alpha correlation only on a subset matching between both

**Comment by thermokarst** [comment]
I like this idea, thanks! @tkosciol, you are welcome to tackle this, just let us know. In the meantime, I will ping @David-Rod & @Oddant1 to see if they are interested, too.

**Comment by tkosciol** [comment]
@thermokarst happy to take a stab at it!

**Comment by thermokarst** [comment]
Fixed in #261
