### ISSUE TITLE
ENH: Route all alpha and beta diversity calculations through q2-diversity-lib

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2-diversity#280]
**Improvement Description**
The following Actions should be made into Pipelines, dependent on Actions from `q2-diversity-lib`:
- `alpha`
- `alpha phylogenetic`
- `beta`
- `beta phylogenetic`

`q2-diversity-lib`, in turn, will dispatch these calls to the best available implementation of the requested method. See https://github.com/qiime2/q2-diversity-lib/issues/22

**Current Behavior**
`core-metrics` and `core-metrics-phylogenetic` call methods from `q2-diversity-lib` for alpha and beta diversity calculations. 
The `alpha` and `beta` Actions, however, are called directly from `q2-diversity`. 

This proposal makes `q2-diversity-lib` uniquely responsible for determining what implementation of a given method should be used. This allows `q2-diversity` to stop caring about what methods have been implemented/constrained in `q2-diversity-lib` at any given moment, and which methods will simply be passed through to an appropriate dependency.

**Proposed Behavior**
- The four actions above are re-implemented as Pipelines
- https://github.com/qiime2/q2-diversity-lib/issues/22 has been closed, and dispatch functions are properly meeting the needs of this issue
- Any other impacted methods (e.g. `alpha-rarefaction` are cleaned up as needed)

**Comments**
1. This will likely require minor changes to other Actions that use these functions - e.g. `alpha_phylogenetic`

**Comment by thermokarst** [comment]
Please see https://github.com/qiime2/q2-diversity/pull/281#issuecomment-665974036 for some modifications to this plan.
