### ISSUE TITLE
Frame is cut when looking at a rarefaction plot

### ISSUE THREAD

**Issue by ElDeveloper** [qiime2/q2-diversity#298]
**Bug Description**

Basically if you open a rarefaction plot and wait for a few seconds and/or start interacting with the zoom; the plot frame gets cut in half, like this:
![rarefaction](https://user-images.githubusercontent.com/2014559/96368738-db399680-1112-11eb-9c45-cef04657914a.gif)

Here is the [original qzv](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdl.dropbox.com%2Fs%2Fg1g5h8xizpeu21o%2F100985_visualization.qzv%3Fdl%3D1).

**Steps to reproduce the behavior**
1. Open a jackknifed plot and go to the ordination

**Expected behavior**
The plot should use the full height available in the window.

**References**
Moved from https://github.com/biocore/emperor/issues/790

**Comment by ElDeveloper** [comment]
cc @antgonza

**Comment by gregcaporaso** [comment]
@ElDeveloper, do you happen to know if this is still an issue? Your link to the original .qzv doesn't work anymore.

**Comment by ElDeveloper** [comment]
@gregcaporaso just had a look and this is no longer a problem!
