### ISSUE TITLE
DOCS: broken link in Adonis docs

### ISSUE THREAD

**Issue by ChrisKeefe** [qiime2/q2-diversity#310]
**Bug Description**

The "for more information" Link at the end of [this page](https://docs.qiime2.org/2021.4/plugins/available/diversity/adonis/) is broken. Here's the bad link, just in case this is only breaking locally or temporarily:
http://cc.oulu.fi/~jarioksa/softhelp/vegan/html/adonis.html

**Questions**
Do we want to link directly to the r-vegan docs, and tell users to search for adonis?
https://cran.r-project.org/web/packages/vegan/vegan.pdf

**Comment by thermokarst** [comment]
It looks like the canonical link to vegan is here (which might be a little less brittle than linking directly to a PDF):

https://cran.r-project.org/package=vegan

(source: https://github.com/vegandevs/vegan)
