### ISSUE TITLE
File name too long

### ISSUE THREAD

**Issue by sjanssen2** [qiime2/q2-diversity#319]
I am abusing qiime2 to analyse some non coding RNA genes. One of the tasks is to test if beta diversity distances vary significantly - which I try to answer via `qiime diversity beta-group-significance`. One of the metadata fields are the secondary structures in dot bracket notation for the RNAs. 
The plugin tries to name some output files like the values in the metadata, here the secondary structure representations, which are ~565 characters long. 

Thus, I get an error like 
```
Plugin error from diversity:

  [Errno 36] File name too long: '/tmp/qiime2-temp-08td9oxj/_.................%5B%5B%5B%5B%5B%5B%5B%5B%5B%5B.%28%28%28%28%28........%28%28%28.%28%28%28%28%28%28%28%28%28.......%29%29%29%29%29.%29%29%29%29%29%29%29..%28%28%28%28%28........%29%29%29%29%29............%29%29%29%29%29.%28%28%28%28%28%28%28.%28%28%28%28%28%28%28.%28%28.%28%28......%28%28%28%28.%28%28........%29%29.%29%29%29%29.....%29%29.%29%29.%29%29%29%29%29%29%29%29%29%29%29%29%29%29.%7B%7B%7B%7B%7B%7B%7B%7B%7B............%28%28%28%28%28.%28%28%28%28%28%28%28%28%28%28..................%29%29%29%29%29%29%29%29%29%29.%29%29%29%29%29........%5D%5D%5D%5D%5D%5D%5D%5D%5D%5D...%3C%3C%3C%3C....%28%28%28%28%28%28%28%28%28%28%28...%28%28%28%28%28%28%28%28%28..%28%28%28%28%28........%29%29%29%29%29...%29%29%29%29........................%29%29%29%29%29%29%29%29%29%29%29%29%29%29%29%29.........%7D%7D%7D%7D%7D%7D%7D%7D%7D..%28%28%28%28%28..%28%28%28%28%28%28......%29%29%29%29%29%29...%29%29%29%29%29.....%3E%3E%3E%3E..%5B%5B.%28%28%28%28%28%28%28..........%29%29%29%29%29%29%29......%7B%7B%7B%7B%7B%7B%7B%7B%7B%7B%7B%7B%7B%7B%7B%7B%7B%5D%5D....%7D%7D%7D%7D%7D%7D%7D%7D%7D%7D%7D%7D%7D%7D%7D%7D%7D..-boxplots.png'

Debug info has been saved to /tmp/qiime2-q2cli-err-t1q20mni.log
```

It would be great if we could find a mechanism to avoid this, e.g. check the filename length and if it exceeds a certain threshold use hash values instead of group names?

https://github.com/qiime2/q2-diversity/blob/e80b507ecb1c5a2a2ee1b44af3e3ae539ab675df/q2_diversity/_beta/_visualizer.py#L195

**Comment by cherman2** [comment]
@ebolyen Does q2templates provide some convenient functionality?

**Comment by ebolyen** [comment]
Nope! Maybe it should, although I haven't seen the likes of this in a while.

**Comment by cherman2** [comment]
I am going to close this issue. Lets re-open if users are still running into this!
