### ISSUE TITLE
Bioenv raises a ValueError when a metadata file has columns with no values, even when other columns have values

### ISSUE THREAD

**Issue by danielhjacobs** [qiime2/q2-diversity#320]
**Bug Description**
If a metadata file has one or more columns with no values in any cells, bioenv will panic, even if there are several other columns with data in every cell. This behavior was not present in qiime version 2020.2, and was likely introduced by https://github.com/qiime2/q2-diversity/commit/76e368fb21d1a9d5a950e4387011680b0fac2859. Originally reported by me on the forums.

**Steps to reproduce the behavior**
1. Use these files: [bioenv_files.tar.gz](https://github.com/qiime2/q2-diversity/files/7555979/bioenv_files.tar.gz)
2. Run the command `qiime diversity core-metrics-phylogenetic --verbose --i-phylogeny rooted-tree.qza --i-table table-trim55126.qza --m-metadata-file 203967.metadata.tsv --p-sampling-depth 300 --output-dir ./output/`
3. Run the command `qiime diversity bioenv --verbose --i-distance-matrix ./output/unweighted_unifrac_distance_matrix.qza --m-metadata-file 203967.metadata.tsv --o-visualization ./output/unweighted-unifrac-bioenv.qzv`

**Expected behavior**
I should see the output:
`Saved Visualization to: ./output/unweighted-unifrac-bioenv.qzv`

**Computation Environment**
- OS: Rocky Linux 8.4 with Conda
- QIIME 2 Release: 2021.4 and 2021.8 tested

**References**
1. https://forum.qiime2.org/t/bioenv-diversity-error-with-qiime-version-2021-4-but-not-with-2020-2/21319

**Comment by lizgehret** [comment]
Confirmed this behavior is still present in QIIME 2 2024.5 amplicon environment (tested on MacOS with intel chip).

**Comment by lizgehret** [comment]
Hey @danielhjacobs thanks for reporting this! I am currently working on a fix that will become available in our current amplicon development environment once merged, and then formally available in the 2024.10 release.

Cheers 🦎
