### ISSUE TITLE
Pip 22.0.4 pip install -e . fails

### ISSUE THREAD

**Issue by Oddant1** [qiime2/q2-diversity#326]
**Bug Description**
When attempting to run `pip install -e .` on q2-diversity with pip 22.0.4, I get an error.

**Steps to reproduce the behavior**
1. Use pip 22.0.4 (it's in our latest dev environment)
2. Run pip install -e . in q2-diversity
3.  See error

**Expected behavior**
Should actually install

**Screenshots**
![image](https://user-images.githubusercontent.com/10642616/165177262-eb5fb03b-d3ee-4d0f-819b-dd5802c5468e.png)

**Computation Environment**
- OS: Linux Mint 20.2
- QIIME 2 Release: Latest dev as of time of writing

**Comments**
1. This is known to pip, and it looks like they have fixed whatever the problem is for their next release
2. If you need a workaround right now, downgrading to 21.3.1 via the command `python -m pip install pip==21.3.1` worked
3. Might affect other repos as well. I was able to `pip install -e .` the framework just fine, didn't try any other repos
4. This should be closed once pip release their fix

**References**
1. https://github.com/pypa/pip/issues/11025
2. https://stackoverflow.com/questions/71410741/pip-uninstall-gdal-gives-attributeerror-pathmetadata-object-has-no-attribute

**Comment by thermokarst** [comment]
Thanks! I ran into this the other day while developing q2cli - hopefully the pip patch makes it out soon.
