### ISSUE TITLE
core-metrics allows even-sampling-effort tables as input

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-diversity#35]
The method should only allows tables that have not been normalized to an even sampling effort as input (e.g. disallow rarefied tables).

**Comment by gregcaporaso** [comment]
This is not currently possible to address without making the type of existing tables:

`FeatureTable[Frequency] % Properties(exclude='uniform-sampling')`

as the property needs to be on the type for the method to be able to use it (`exclude` doesn't tell it to use only tables that don't have this property. 

So, the options are to leave this as is for now and users can accidentally pass an already-rarefied table, or to remove the rarefaction step from this method and make the input type `FeatureTable[Frequency] % Properties('uniform-sampling')`. This seems like it'd work, but it'd be a little less convenient for the user. I'm ok with either of these options. @jairideout, what do you think?

**Comment by gregcaporaso** [comment]
After some internal discussion we've decided a few things:

1. We're probably going to change how `exclude` works to support this. We'll want this for methods that shouldn't be run on a `uniform-sampling` (e.g., rarefied) table, such as `ancom` and `rarefy`. 

2. `core-metrics` should not include a rarefaction step so users can provide `uniform-sampling` tables that have been generated with other compatible types of normalization. 

3. We don't want to remove the rarefaction step from core-metrics right now. We're worried that  if we have users create rarefied tables in the tutorials, and we're not able to specify that a table can't have `Property('uniform-sampling')` using `exclude`, users might fall into a trap of providing the `uniform-sampling` table to methods like ANCOM, which should be given raw (not-rarefied) tables. 

So, we'll address the first point and then we'll address the second point. Once the first point is addressed, we'll update methods like ANCOM to specify that they cannot take a rarefied table.

**Comment by wasade** [comment]
The input to ANCOM (as an example) is not exactly raw though, as often times you want to filter low abundance OTUs and samples with only a handful of sequences.

**Comment by jairideout** [comment]
No longer relevant since the `uniform-sampling` property was removed in #114 and https://github.com/qiime2/q2-feature-table/pull/116
