### ISSUE TITLE
The difference between the simpson and simpson_e indices

### ISSUE THREAD

**Issue by WangLitt** [qiime2/q2-diversity#353]
Sorry to bother you, but can you tell me the difference between the simpson and simpson_e indices？
And how the size of the number relates to the size of the diversity

**Comment by gregcaporaso** [comment]
Hi @WangLitt, We provide this type of support on the QIIME 2 Forum. Could you please post your question there? Thank you!

**Comment by WangLitt** [comment]
Sure. I'll post these question there. Thank you for your response!
