### ISSUE TITLE
"Faith Pd" is hard-coded as the axis label in alpha group significance box plots

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-diversity#48]

**Comment by thermokarst** [comment]
Update [here](https://github.com/qiime2/q2-diversity/blob/master/q2_diversity/_alpha/alpha_group_significance_assets/src/axis.js#L34).

**Comment by thermokarst** [comment]
@gregcaporaso: should we rename to something more generic (e.g. 'Metric'), or should we provide an option to specify the metric name as an argument, or some other option?

**Comment by jairideout** [comment]
I think viewing `SampleData[AlphaDiversity]` as a `pd.Series` will have the metric name available via `.name`. Can you try that out?
