### ISSUE TITLE
error message coming from skbio in `alpha/beta_phylogenetic` refers to "otu ids"

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-diversity#59]
We should update this to reference feature ids for clarity:

```
MissingNodeError: All ``otu_ids`` must be present as tip names in ``tree``.
```

**Comment by johnchase** [comment]
A long these same lines one of the metrics in `diversity.methods.alpha` is "observed_otus" it may make sense to rename this "feature_counts" or something similar

**Comment by jairideout** [comment]
@johnchase, we decided not to change the method name, see my comment [here](https://github.com/qiime2/q2-diversity/pull/74#discussion_r92720202) for details. I created a separate issue to track this: #77

**Comment by johnchase** [comment]
👍  That sounds good!
