### ISSUE TITLE
include descriptions of stats and p-value correction methods in visualizations

### ISSUE THREAD

**Issue by gregcaporaso** [qiime2/q2-diversity#66]
**Current Behavior**
During the phx workshop we noticed that there wasn't sufficient detail (e.g., what multiple comparisons method is applied - it's FDR correction as implemented in stats-models) in the alpha group-significance visualization.  This is probably true of other visualizations as well. 

**Proposed Behavior**
We should add this information to the visualizations.

**Comment by jairideout** [comment]
[forum x-ref](https://forum.qiime2.org/t/kruskal-wallis-test-of-alpha-diversity/2211/14?u=jairideout)

**Comment by marwa38** [comment]
Any updates on adding the q or p values on the graphs?

**Comment by thermokarst** [comment]
Hi @marwa38 - no updates on this - we would gladly welcome a contribution, if you're interested! Just let us know!

**Comment by cherman2** [comment]
We definitely should do this! I believe this a goal for q2-vizard. Closing issue.
