### ISSUE TITLE
Add ability to filter alpha correlation results based on metadata category

### ISSUE THREAD

**Issue by ceolder** [qiime2/q2-diversity#68]
This would save time by not having to run alpha correlation separately for different metadata categories of interest.

**Comment by jairideout** [comment]
👍

**Comment by thermokarst** [comment]
@ceolder: I don't think this issue is relevant anymore --- alpha correlation supports multiple metadata categories in the interactive visualizations (merged in #44, available since 2.0.5). If I am misunderstanding this issue feel free to reopen and provide some additional details. Thanks!
