### ISSUE TITLE
Add category selection parameter to `bioenv`

### ISSUE THREAD

**Issue by jakereps** [qiime2/q2-diversity#73]
**Improvement Description**
> It could be useful to specify categories as an optional parameter to bioenv, e.g., to reduce runtime on very large metadata maps (such as from qiita) and/or to avoid certain categories.

**References**
Branched from #56 and recommended by @nbokulich

**Comment by cherman2** [comment]
Closing due to lack of interest in the method. Feel free to re-open if there is interest in this functionality.
