### ISSUE TITLE
add diversity data to sample metadata

### ISSUE THREAD

**Issue by nbokulich** [qiime2/q2-diversity#76]
Something akin to qiime1's [``add_alpha_to_mapping_file``](http://qiime.org/scripts/add_alpha_to_mapping_file.html), but perhaps generalized to incorporate other diversity data (e.g., PCoA coordinates) or even other data types.

This could generalize to a qiime-2 version of [``merge_mapping_files``](http://qiime.org/scripts/merge_mapping_files.html) if the method can accept a broader range of inputs (e.g., artifact or tsv).

**Comment by jairideout** [comment]
👍  We're planning to overhaul metadata in QIIME 2 (unknown ETA) so that artifacts can be viewed/interpreted as metadata. I created an issue to track this, with a little more detail:

https://github.com/qiime2/qiime2/issues/200

Closing in favor of that issue.

**Comment by nbokulich** [comment]
Awesome. Thanks!
