### ISSUE TITLE
Empty directory output in core-metrics

### ISSUE THREAD

**Issue by m-ocejo** [qiime2/q2-diversity#78]
I am importing dada2 table (following the tutorial in its website) to qiime2:
- firstly convert seq_table.txt to hdf5 biom table format (seqtable_qiime.biom).
- then with qiime import tools, convert it to an artifact for qiime2 with this command 
    ```qiime tools import --input-path seqtable_qiime.biom --type "FeatureTable[Frequency]" --source-format BIOMV100Format --output-path feature-table```

I did the same with rep_set.nochimeras.OTUs.fasta
    ```qiime tools import --input-path rep_set.nochimeras.OTUs.fasta --output-path rep_seqs-table --type "FeatureData[Sequence]"```
and Generate the tree for phylogenetic diversity analyses.

Then, I try to run the command `qiime diversity core-metrics`, it didn´t give any error message. Instead, the terminal showed the 979 sequences (separated by space) of my biom table. When I go to the directory created, it has 0 elements.
Both `.qza` inputs have the semantic type needed.

Any help would much be appreciated!
Best!

**Comment by gregcaporaso** [comment]
Hi @m-ocejo, Would you mind re-posting this question to the [QIIME 2 Forum](https://forum.qiime2.org). We try to provide this type of technical support there. You can log in there with your GitHub account, so it won't be necessary for you to create a new account. Thanks!
