### ISSUE TITLE
Alpha Correlation X-Axis Number Formatting

### ISSUE THREAD

**Issue by thermokarst** [qiime2/q2-diversity#88]
Currently the [Alpha Correlation plots](https://view.qiime2.org/visualization/?type=html&src=https%3A%2F%2Fdocs.qiime2.org%2F2017.2%2Fdata%2Ftutorials%2Fmoving-pictures%2Fcm1441%2Fevenness-correlation.qzv) look a little weird:

<img width="1117" alt="screen shot 2017-02-12 at 5 21 31 pm" src="https://cloud.githubusercontent.com/assets/274668/22866630/bbf6707a-f147-11e6-9a89-4e7e35d45895.png">

The years are formatted with thousands and decimal place separators. Maybe we do some kind of int test (for decimals) and drop commas (for thousands)?

**Comment by maxvonhippel** [comment]
I think this is happening [here](https://github.com/qiime2/q2-diversity/blob/master/q2_diversity/_alpha/alpha_correlation_assets/src/render.js#L20), in the axis scaling.  I'm happy to work on this.

If we keep year-level precision, then it no longer makes sense to have that many ticks on the x axis.  (There would be 10 identical `2008` ticks.)  In which case the axis scaling would happen differently.  I am imagining that, in the above example, there would be three tick marks: 2007, 2008, and 2009.  The chart would still be equally wide, it's just that the ticks would be farther apart.  Is this what you have in mind?  Or do you envision a different implementation?

**Comment by thermokarst** [comment]
Thanks for taking a look at this @maxvonhippel! Generally speaking I like where you are going with this, but we actually need to be able to support decimal numbers when present, which doesn't quite line up with your suggestion of "year-level precision" (apologies if I misunderstood your suggestion!). The linked qzv above doesn't have any decimal metadata categories, but you can imagine something like pH, where the values are 7.2, 6.8, etc.

Maybe one approach is to replace the blanket scaling of the domain by 0.03 (which happens in that line of code you linked to above) with some kind of conditional testing to get sane x-axis scales.

---

Some examples of input values, and the resultant domains and ticks that make sense (to me, at least):

### Integer
X Data Values: [2008, 2009]
Domain: [2007, 2010]
Tick Step Size: 1
Number of Ticks: 4

This is what you are describing above, the net result is that there are fewer tick marks, and they are placed in locations that line up with the type of data (whole numbers).

### Decimal
X Data Values: [3.2, 5.6, 7.5, 9.1]
Domain: [3, 9.5]
Tick Step Size: 0.5
Number of Ticks: 13

---

Note, we probably don't want to over-engineer this right now, since this problem will be strongly impacted by our discussions around metadata typing. :neckbeard: 

Sounds like this would be a great task for you to tackle next! Let me know what I can help with! 🎉

**Comment by maxvonhippel** [comment]
@thermokarst I think we are almost on the same page with this.  When I said "year level precision", I meant only in the context of when the user selected "Year" for category, as in the example `qzv`.  I did not mean to say that months or days or other categories should be somehow cast differently.

I definitely agree that there is a risk of over-engineering.

Would it be appropriate to delegate the job of formatting the axis relative to the selected category to `d3`?  In other words, if `d3` saw that I wanted Year, Month, or Day as my x-axis category, it would automatically create a `d3` style date stamp x axis and scale appropriately.  And then any other numeric values would be simply treated as normal numeric values.

I don't think this is an unreasonable amount of work for `d3`.  It seems fairly straight-forward to me that the `d3` code (render.js, in this case, I think?) could recognize the words "Year", "Month", and "Day", and elect the correct [d3 date format](https://github.com/d3/d3/blob/master/API.md#time-formats-d3-time-format) accordingly.

**Comment by maxvonhippel** [comment]
Let's move conversation [to the PR](https://github.com/qiime2/q2-diversity/issues/113) :) .

@thermokarst I'm ready for review, thanks!
