### ISSUE TITLE
add Mantel visualizer

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-diversity#94]

**Comment by gregcaporaso** [comment]
The plan here will be to add a visualizer `mantel`, and a new method, `metadata-distances`(?). `mantel` will take two distance matrices and produce a scatterplot and mantel stats. `metadata-distances` will take a sample metadata column and produce a new distance matrix of Euclidean distances between all samples. 

In the future, we'll add a `Pipeline`, `beta-correlation`, which combines these two steps. We can also generalize `metadata-distances` to take other relevant distance metrics.
