### ISSUE TITLE
add method to compute distance matrix from numeric metadata categories

### ISSUE THREAD

**Issue by jairideout** [qiime2/q2-diversity#95]

**Comment by gregcaporaso** [comment]
This is covered in [@jairideout's skbio cookbook recipe](http://nbviewer.jupyter.org/github/biocore/scikit-bio-cookbook/blob/master/Exploring%20microbial%20community%20diversity.ipynb).

**Comment by jairideout** [comment]
This currently can't be implemented because methods/visualizers require at least one input artifact. Should be an easy fix in the framework to support this.

**Comment by gregcaporaso** [comment]
When it's possible for us to support this, we can promote the current `_metadata_distance` function to a method.

**Comment by gregcaporaso** [comment]
replaced by qiime2/q2-metadata#5
